[package]

name = "rust-raytracer"
version = "0.0.1"
authors = ["Par Bohrarper <par.bohrarper@gmail.com>"]

[lib]
name = "rust_raytracer"
path = "src/lib.rs"

[dependencies]
vecmath = "0.3.1"

[profile.release]
debug = true
